### ISSUE TITLE
Changes to Settings

### ISSUE THREAD

**Issue by kambala-decapitator** [SylvainCecchetto/xbmc#70] opened 2019-06-01 21:14 UTC
1. "on this computer" :) "Device" should be much better (also for iOS/Android/etc), but maybe not worth it.
![Screen Shot 2019-06-01 at 20 53 07](https://user-images.githubusercontent.com/1557784/58753648-460d1200-84cb-11e9-90d3-7c95c8754468.png)

2. Probably Airplay tab should be removed completely as ATV handles airplay natively
![Screen Shot 2019-06-01 at 20 53 50](https://user-images.githubusercontent.com/1557784/58753652-64730d80-84cb-11e9-8f71-94e384e16e15.png)

**Comment by fuzzard** [comment] 2019-08-13 03:45
Is the airplay support setting as Kodi itself as a receiver? 
I guess do you just drop it and assume if your airplaying to it, you just use the native implementation. Does Kodi actually keep any info as an airplay receiver (playcount, watched status, etc) or just enables it on other devices as a target?

If it doesn't track any info or provide any value, I'm all for dropping it, and then we can drop the shairplay dependency as well

**Comment by sy6sy2** [comment] 2019-08-13 06:07
> Is the airplay support setting as Kodi itself as a receiver?

Yes, by enabling this toggle you put Kodi as an Airplay receiver (if you move to expert view you can choose between audio+video airplay or only audio).

> I guess do you just drop it and assume if your airplaying to it, you just use the native implementation.

Totally agree

> Does Kodi actually keep any info as an airplay receiver (playcount, watched status, etc) or just enables it on other devices as a target?

Don't know if Kodi keep information but I can confirm that kodi receive metadata like music name and artist while it is in airPlay receiver mode.
I will have a look to be sure that Kodi does not use any information from AirPlay. Also, I'm not even sure that the "Kodi-AirPlay" mode works on the Apple TV.

Edit: I can confirm that the Kodi AirPlay feature works on tvOS with Kodi-yab. Maybe some people still want to stream music from an Apple device directly to kodi AirPlay instead of the native tvOS AirPlay?

**Comment by fuzzard** [comment] 2019-08-13 08:01
That's the thing though, the ATV implementation will always be better. So if Kodi doesn't add anything extra that adds value by it being done inside Kodi, why bother.
As a new platform, I think we can take liberties with implementation details as there is no official past version. I'm happy to keep it if it adds value, but if there is none, why not use the following gold standard of apples implementation

**Comment by sy6sy2** [comment] 2019-08-13 08:11
I also vote to hide "Kodi-AirPlay" section on Apple TV platform. I think that this section could confuse a "lambda" user because there is also the AirPlay from Apple TV.

Also 1 point for "AppleTV-AirPlay", if I stream audio from my iPhone I can see the album art, this is not the case with Kodi-AirPlay.
Also, video AirPlay with Kodi is broken since iOS9, obviously this is not the case with native AirPlay.

I can open PR to hide this section and we will see what the team think about that ;-)

**Comment by fuzzard** [comment] 2019-08-17 13:32
item 1 was PRd and merged into master.

Have just pulled in item 2 in the main branch. Have done a full build/run, and libplist and libshairplay are both correctly not built and found, settings are hidden, and small runtime test for regular use seems ok.

Good to close this one i think

**Closed as completed** 2019-10-22 17:18 UTC
